### PR TITLE
Added the 'capture-limits' section to the config.

### PR DESCRIPTION
**Pull request by lokka30**
I've began work on #34.

Brand new to the SpadesX code-base, and also C for that matter. 🙂 

# Implementation details

- Each map has its own capture limit value. These are specified in the map's config file, e.g. `Border_Hallway.json`.
- If a map's config is missing the capture limit setting, then SpadesX will assume a default value via a macro in the source code.

# To-do

- [x] Brainstorm what the modified configuration will look like.
- [ ] Move score limit into `MapStruct.h`.
- [ ] Add macro in `MapStruct.h` to specify a default capture limit value of `10`.
- [ ] Remove score limit from `GamemodeStruct.h`.
- [ ] Change usages of the gamemode score limit to map-based score limits.
- [ ] Initialise the score limit of maps when they are loaded by reading the config.
- [ ] Testing & fixing.

# Code points which will likely need to change:

- [IntelTent.c#L242-L245](https://github.com/lokka30/SpadesX/blob/master/Source/Server/IntelTent.c#L242-L245)
- Gamemodes.c [L49](https://github.com/lokka30/SpadesX/blob/master/Source/Server/Gamemodes/Gamemodes.c#L49) and [L79](https://github.com/lokka30/SpadesX/blob/master/Source/Server/Gamemodes/Gamemodes.c#L79)

### CODE REVIEW

**Comment by Haxk20** [comment]
GamemodeStruct will still have an define (#define) for the limits.

The macros we have in SpadesX for reading from config json files will just use this default if the config option is not found.

**Comment by Haxk20** [comment]
IntelTent code needs no modifications.

In the other 2 lines you specified you just need to remove the hardcoded value and initialize this variable of this struct once we have the limit from config.

**Comment by Haxk20** [comment]
> IntelTent code needs no modifications.
> 
> In the other 2 lines you specified you just need to remove the hardcoded value and initialize this variable of this struct once we have the limit from config.

(Remove the 2 lines and initialize the variable in the file where we load the map config.

**Comment by lokka30** [comment]
I'll close this PR and attempt to contribute another time. :)

**Pull request closed without merging**
