### PR TITLE
Added Maps repo to Extern.

### PR DESCRIPTION
**Pull request by lancilloty**
Fixes:
- Ensures the development of multi-map support will work with the default maps out of the box.

Changes proposed in this pull request:
- Adding Maps repo to Extern.

### CODE REVIEW

**Comment by Haxk20** [comment]
Generally i have nothing against it as it doesnt break anything. But its such a pointless PR at this time that it simply doesnt make sense yet. When we add the maps repo as submodule it will already be with a full blown support where it will read the maps automatically and etc.

So at this time i will close it. Truly wait until the map support is there fully and then we can add it as submodule.

**Comment by lancilloty** [comment]
@Haxk20 What if I changed the config so the Border_Hallway map being used what the one in the Maps repo & I cleaned up the Resources folder for that?

**Comment by Haxk20** [comment]
> @Haxk20 What if I changed the config so the Border_Hallway map being used was the one in the Maps repo & I cleaned up the Resources folder for that?

There is still no point. I know you want the map repo to be used. But the code simply isnt ready for it. It will be utilized dont worry about it. But there is simply not that many maps there and i do not have the time to add the code to utilize the repo as i have finals in few weeks. So just wait.

**Comment by lancilloty** [comment]
@Haxk20 Frankly I just never messed around with submodules much so I used this excuse to learn to play with them & figured it might save you a bit of time. But no worries, I'll have patience :)

**Pull request closed without merging**
